name: 反馈 Bug
description: 通过 github 模板进行 Bug 反馈。
title: "描述问题的标题"
body:
  - type: textarea
    id: expect
    attributes:
      label: 期望结果
      placeholder: 请填写

  - type: textarea
    id: actual
    attributes:
      label: 实际结果
      placeholder: 请填写

  - type: textarea
    id: remarks
    attributes:
      label: 补充说明
      description: 可以是遇到这个 bug 的业务场景、上下文等信息。
      placeholder: 请填写
